import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/db";
import { generateAITripItinerary } from "@/lib/aiTripPlanner";
import { createNotification } from "@/lib/services/notification-service";
import { getLocalServerSession } from "@/lib/local-auth";
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST(req: NextRequest) {
  try {
    const session = await getLocalServerSession();
    if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    const userId = session.user.id;
    const { tripId, preferences } = await req.json();
    if (!tripId) return NextResponse.json({ error: "Trip ID required" }, { status: 400 });

    const trip = await prisma.trip.findFirst({
      where: { id: tripId, OR: [{ userId }, { collaborators: { some: { userId, status: "ACCEPTED" } } }] },
      include: { destinations: { orderBy: { orderIndex: "asc" } } },
    });
    if (!trip) return NextResponse.json({ error: "Trip not found" }, { status: 404 });
    if (trip.destinations.length === 0) return NextResponse.json({ error: "Trip has no destinations" }, { status: 400 });

    const userPref = await prisma.userPreference.findUnique({ where: { userId } });
    const dest = trip.destinations[0];

    let interests = preferences?.interests || [];
    if (!interests.length && userPref?.interests) {
      try { interests = JSON.parse(userPref.interests as string); } catch { interests = []; }
    }

    const aiItinerary = await generateAITripItinerary({
      destination: dest.name,
      startDate: trip.startDate.toISOString().slice(0, 10),
      endDate: trip.endDate.toISOString().slice(0, 10),
      budgetUsd: Number(trip.totalBudget || 1000),
      travelers: trip.travelerCount,
      travelStyle: trip.travelStyle,
      interests,
      pace: preferences?.pace || userPref?.travelPace || "MODERATE",
    });

    const days = aiItinerary.days.map((day) => ({
      dayNumber: day.day,
      date: new Date(day.date),
      title: day.title,
      dailyCost: day.estimatedCostUsd,
      items: day.activities.map((activity) => ({
        title: activity.name,
        description: `${activity.description}\n\n${activity.whyRecommended}`,
        location: activity.name,
        latitude: activity.latitude || dest.latitude,
        longitude: activity.longitude || dest.longitude,
        timeSlot: activity.time >= "18:00" ? "EVENING" : activity.time >= "12:00" ? "AFTERNOON" : "MORNING",
        startTime: activity.time,
        endTime: activity.time,
        estimatedCost: activity.estimatedCostUsd,
        category: activity.category.toLowerCase(),
        tags: [activity.category, aiItinerary.source, `AI score ${activity.aiScore}`],
        notes: aiItinerary.aiMethod,
        crowdLevel: activity.aiScore > 0.82 ? "High" : "Moderate",
        weatherNote: aiItinerary.source === "ollama-llm" ? "Generated by Ollama local LLM" : aiItinerary.warning || "Generated by local fallback planner",
      })),
    }));

    await prisma.itinerary.deleteMany({ where: { tripId } });

    const itinerary = await prisma.itinerary.create({
      data: {
        tripId,
        generatedBy: aiItinerary.source === "ollama-llm" ? "ollama-local-llm" : "local-rule-based",
        days: {
          create: days.map((day) => ({
            dayNumber: day.dayNumber,
            date: day.date,
            title: day.title,
            dailyCost: day.dailyCost,
            items: {
              create: day.items.map((item, idx) => ({
                title: item.title,
                description: item.description,
                location: item.location,
                latitude: item.latitude,
                longitude: item.longitude,
                timeSlot: item.timeSlot as any,
                startTime: item.startTime,
                endTime: item.endTime,
                estimatedCost: item.estimatedCost,
                currency: trip.currency,
                category: item.category,
                tags: JSON.stringify(item.tags),
                notes: item.notes,
                crowdLevel: item.crowdLevel,
                weatherNote: item.weatherNote,
                orderIndex: idx,
              })),
            },
          })),
        },
      },
      include: {
        days: { orderBy: { dayNumber: "asc" }, include: { items: { orderBy: { orderIndex: "asc" } } } },
      },
    });

    await prisma.trip.update({ where: { id: tripId }, data: { status: "PLANNED" } });
    await createNotification({
      userId,
      type: "ITINERARY_GENERATED",
      title: "Itinerary Generated! 🗺️",
      message: `Your itinerary for "${trip.title}" is ready with ${days.length} days of activities. AI method: ${aiItinerary.aiMethod}`,
      link: `/trip/${tripId}`,
    });

    return NextResponse.json({ ...itinerary, localAi: aiItinerary }, { status: 201 });
  } catch (error) {
    console.error("Generate itinerary error:", error);
    const message = error instanceof Error ? error.message : "Failed to generate itinerary";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
